apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-game-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: math-game
  template:
    metadata:
      labels:
        app: math-game
    spec:
      containers:
      - name: math-game
        image: jay0421/fun_math:latest
        ports:
        - containerPort: 3000
