apiVersion: v1
kind: Service
metadata:
  name: math-game-service
spec:
  selector:
    app: math-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Update targetPort to match the port your application is running on
  type: LoadBalancer
